### ISSUE TITLE
列表下方分页页数的显示问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#106]
如图所示：
![image](https://f.cloud.github.com/assets/3068259/2319849/318f7e44-a385-11e3-9e16-4417ad0de968.png)
当商品数量过多，下方的页数仍然每页都显示，我们现在商品种类还算少，如果商品再多一点，整个页面就被占了！需要把中间的页数都省略掉!

**Comment by tsq** [comment]
@guanbo 请关闭 issue106
