### ISSUE TITLE
商户详情中存在的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#108]
![image](https://f.cloud.github.com/assets/3068259/2320076/c558e0e0-a388-11e3-943f-f1c8c0f631b0.png)
如上图所示，`编辑`与`选择其他商户`这两个按键太夸张了，红色圈出的地方在页面中应该不用显示，旁边的owner头像也应该去掉。

**Comment by tsq** [comment]
@guanbo 请关闭 issue108
