### ISSUE TITLE
演示数据优化

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#115]
## 问题

当前演示用的18912345678下面存在测试时产生的数据，在演示的时候给人感觉不够正式。
## 解决方式
- 删除测试时没有用的垃圾数据
- 规范演示用数据的命名，尽量模拟真实数据。例如将商店test1可以改名为江宁店或者泛盈2号直营店等。

**Comment by chenshun** [comment]
更改不和规范的商店名、会员姓名、雇员姓名以及部分商品名，现在还是不够正式，等待删除功能。

**Comment by guanbo** [comment]
发起多个issue需求，针对不同对象的删除功能。
