### ISSUE TITLE
编辑用户管理-信息都是必填项！

### ISSUE THREAD

**Issue by wangjing199408** [extensivepro/exprocrm#119]
![image](https://f.cloud.github.com/assets/6337119/2354985/6c675918-a5d0-11e3-9bab-10424c2a6742.png)

在性别选择点击上，感觉不太明显！

**Comment by guanbo** [comment]
@wangjing199408 这个问题你尝试的改下：
- 姓名、身份证、电子邮箱在这个阶段我们是选填的，但电话是必填。
- 你可以在网上(例如：github)找一个好点的switch来替代现有的。
