### ISSUE TITLE
积分管理，2个累计积分栏。

### ISSUE THREAD

**Issue by wangjing199408** [extensivepro/exprocrm#120]
![image](https://f.cloud.github.com/assets/6337119/2355022/806d4f16-a5d1-11e3-98da-7f531bcc25ce.png)

**Comment by chenshun** [comment]
建议`累积积分`改为`当前积分`。

**Comment by guanbo** [comment]
同意 @chenshun 的意见，请 @wangjing199408 修改。

**Comment by guanbo** [comment]
@wangjing199408 下次记得在fixed #120 中间是有空格的，否则格式不对不能自动关闭issue。
