### ISSUE TITLE
清楚后台无用数据

### ISSUE THREAD

**Issue by leonardean** [extensivepro/exprocrm#139]
诸如无用商店，员工

**Comment by guanbo** [comment]
有哪些，请给出具体场景。

**Comment by leonardean** [comment]
如：
![img](https://raw.github.com/leonardean/ImgUpload/master/0F9025DA-DA33-4A3E-9F86-1C286926842E.png)

**Comment by guanbo** [comment]
这些店铺还是要保留一些的，已经在 #115 中请 @chenshun 优化。改些有意义的名字，删除一部分。
