### ISSUE TITLE
库存记录没有区分是进货还是出货

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#144]
![image](https://f.cloud.github.com/assets/3068259/2394859/31bc36ca-a9be-11e3-8818-a1144afda9ef.png)
如上图，部分出库数量仍然是正数，没有表现出是出库还是入库，出库数量应显示为负，
右侧`支出`也要调整：
方案①：`支出`改为`金额`，进货时金额显示为负；出货为正，区分开；
方案②：加入一列`收入`，用来显示出货时的金额，与进货区分开；
个人感觉方案②更直观一点 
@guanbo 请指示

**Comment by guanbo** [comment]
- 加入`类型`：`进货`、`核销`
- `数量`用正负表示
- `支出`调整为`总金额`
-  新增`均价`。

**Comment by chenshun** [comment]
`总金额`不用正负表示可能会让用户误认为`核销`也同`进货`一样是花了钱的。

**Comment by guanbo** [comment]
> 总金额不用正负表示可能会让用户误认为核销也同进货一样是花了钱的。

同意

**Comment by tsq** [comment]
@chenshun  核销的意思是不是就是与进货相反的出货。

**Comment by guanbo** [comment]
> @chenshun 核销的意思是不是就是与进货相反的出货。

核销 = 库存商品损失，报销掉了。从库存中减除
