### ISSUE TITLE
商户管理中，无法选择其他商户

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#145]
### 步骤
1. 进入泛商汇RMS系统
2. 点击`商户管理`，`当前商户`
3. 点击`选择其他商户`
### 结果

![image](https://f.cloud.github.com/assets/3068259/2394955/e15b3d72-a9c0-11e3-8158-1b7485165368.png)
商户列表为空
### 期望

可以正常实现

**Comment by tsq** [comment]
@chenshun  @guanbo  这个bug昨天修复过，只是s.fankahui.com没有同步最新的代码。

**Comment by chenshun** [comment]
先关闭。
