### ISSUE TITLE
选择日期中的英文字符应改为中文

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#150]
如下图：
![image](https://f.cloud.github.com/assets/3068259/2395178/1b723a34-a9c5-11e3-8d45-3f758db5d5e2.png)
建议将图中的英文字符改为中文，考虑美观，周日至周一的英文字符可以保留。

**Comment by leonardean** [comment]
效果为
![i](https://raw.github.com/leonardean/ImgUpload/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202014-03-13%20%E4%B8%8A%E5%8D%8810.56.30.png)
