### ISSUE TITLE
主界面菜单

### ISSUE THREAD

**Issue by leonardean** [extensivepro/exprocrm#158]
# 问题

主页面菜单打开子菜单时没有动画，略显唐突，尤其是在一个子菜单打开的时候点击打开另一个二级目录，则之前的二级目录就会收起。由于界面变化过于突然，超出用户期望预计，可能使得用户短时间内不知所措。
# 期望

点击打开二级菜单是有下拉动画，且可以同时打开/关闭多个二级菜单

**Comment by tsq** [comment]
@leonardean  已修改，请关闭。
