### ISSUE TITLE
主菜单页脚

### ISSUE THREAD

**Issue by leonardean** [extensivepro/exprocrm#159]
# 问题

目前主菜单页脚超出屏幕高度，即便空间上完全可以放在同一屏幕内。当用户无意滚动鼠标时使得整个app界面变动，不利于用户培养一致性操作习惯和操作结果预期。
# 期望

整个app的UI框架在同一屏幕内，即便有时内容超出屏幕宽度，比如当用户同时看50条记录的时候，用户滚动鼠标时仅使界面内部content box滚动，而非整个UI框架

**Comment by tsq** [comment]
@leonardean  已修改，请关闭。
