### ISSUE TITLE
批量删除鼠标移动距离较远，建议把删除放置右侧

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#164]
![image](https://f.cloud.github.com/assets/3068259/2408079/e4468844-aa96-11e3-9862-3f82ff7301f0.png)
如上图所示，点击右上角删除图标，列表最左侧出现删除选项，很不合理，建议移至右侧，方便操作。

**Comment by guanbo** [comment]
不建议调整，删除数据危险操作，就要放远点。
