### ISSUE TITLE
积分管理界面完善

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#165]
![2014-03-13 11 59 26](https://f.cloud.github.com/assets/712444/2411535/829c0f4c-aac8-11e3-9651-ac5862d94c44.png)
- 会员ID和商户ID调整为会员名和商户名
- 第一列放积分发生时间
- 第二列会员名
- 第三列积分数量

**Comment by tsq** [comment]
@guanbo  ‘会员ID和商户ID调整为会员名和商户名’。关于这个调整，是不是还要通过这个ID，从后台把真正的name给拿回来，还是就直接填id那窜数字。

**Comment by guanbo** [comment]
你觉得用这个系统的人是机器？
