### ISSUE TITLE
商户销售统计管理

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#166]
- 在销售统计中增加商户品类的排名
- 统计列表中要有单品的销量和销售额
- 畅销商品可以设置安全库存，可以根据销售速度和周期给出建议安全库存值

**Comment by leonardean** [comment]
这些是显示在哪个页面，另外目前没有品类接口

**Comment by guanbo** [comment]
> 这些是显示在哪个页面，另外目前没有品类接口

![2014-03-14 11 14 29](https://f.cloud.github.com/assets/712444/2417643/d4273dc4-ab26-11e3-95b8-f53922b1429b.png)
- 可以放在这个图表的下方。
- 销量的单品统计目前还没有品类。
