### ISSUE TITLE
控制面板

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#167]
- 在主菜单第一个位置放置控制面板，作为默认首页。
- 控制面板反应出如下当天内当前商户的实时指标：
  - 销售额/会员销售额
  - 现金流
  - 进货
- 同时反应下列排行
  - 店铺销售额排行榜
  - 单品销量排行榜

**Comment by leonardean** [comment]
> 现金流

此处我由于不太明白现金流的含义，特意查了下。现金流大多用于统计时间段内数目较杂但是范围涵盖所有的逐条项目，用于做总账。比如一个商户，他的现金流统计里应该包括，水费，电费，网费，房租，贷款，还贷，员工工资，进货，会员充值，销售，退货。我这块没法涉及到所有的费用项目，只能说我们这块的数据会是商户现金流上的一部分。如果硬要做现金流的话，我们能做的好像就是把销售额和进货展开来就是的了。而此处既然有了销售额和进货的信息，所以以为现金流可以省去

**Comment by guanbo** [comment]
> 水费，电费，网费，房租，贷款，还贷，员工工资，进货，会员充值，销售，退货。

是很多部分确实，但后期会加入。

> 而此处既然有了销售额和进货的信息，所以以为现金流可以省去

销售额部等于现金，会员的预存款也是现金，但会员用储值消费的时候并不产生现金。
