### ISSUE TITLE
进货统计，显示统计图时，之前会有一个小图先显示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#185]
### 步骤
1. 进入RMS系统，点击`进货统计`
2. 点击`前30天`
### 结果

可以看到统计图展示出来时，会显示一个小图，如下：
![image](https://f.cloud.github.com/assets/3068259/2443862/7c0549f0-ae42-11e3-8441-ccfbc17f2eeb.png)
### 期望

去掉这个小图的显示，直接显示要显示的内容。

**Comment by leonardean** [comment]
> 显示一个小图，如下

截图手真快啊。。
