### ISSUE TITLE
CRM统计

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#189]
## 需求

以图表统计的形式展现出会员的情况。宏观上给用户直观的了解到会员活动的趋势，包括：
- 会员的消费额的趋势图
- 会员归属店消费的占比
- 会员热门的单品

微观层面展现会员个体的情况。包括：
- 会员消费额增幅排行
- 会员消费额累计排行
- 会员消费额衰退排行
## 任务
- 绘制简单原型，以图表结合的方式展现
- 对应会员个体和单品、商店可以查看具体的情况

**Comment by leonardean** [comment]
这里查看会员的消费情况都是指在该商户旗下商店里的消费情况，还是让一个商户查到他会员在所有商户的消费信息

**Comment by leonardean** [comment]
> 会员消费额增幅排行
> 会员消费额衰退排行

此处是要取得单个会员的消费额趋势，而通常微观的趋势不具有统计意义，如同github中的punch card感觉更能体现出单个会员的动态和价值，或者平均每周/月的消费次数/消费额

**Comment by guanbo** [comment]
> 这里查看会员的消费情况都是指在该商户旗下商店里的消费情况，还是让一个商户查到他会员在所有商户的消费信息

先考虑在当前商户的情况。

> 此处是要取得单个会员的消费额趋势，而通常微观的趋势不具有统计意义，如同github中的punch card感觉更能体现出单个会员的动态和价值，或者平均每周/月的消费次数/消费额

这个是找出有价值客户
