### ISSUE TITLE
今天用PAD进货，上传之后在商品管理中所有的商品都有两条记录

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#193]
如下图：
![image](https://f.cloud.github.com/assets/3068259/2458082/d6af2f34-af45-11e3-8394-a800b3fea603.png)
上面是今天刚进货的商品，每种都有两条一模一样的记录。

**Comment by tsq** [comment]
在用pad新建商品时，客户端和服务器端通信，会发两次item。不是rms端的问题。已挂到 王延之身上。
