### ISSUE TITLE
建议：商户范围内的单品销量排行

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/exprocrm#202]
几个建议（有些可能是我不熟悉系统，不知道如何操作造成）：
1.无法得知哪种商品销量较大；
2.会员分析力度不够，无法得知哪个会员的贡献度最大，无法查询会员的消费记录；
3.会员余额不支持排序；
4.销售及相关记录支持导出excel等功能
5.储值流水能明显看出账户中的余额是增还是减，比如前面加上“+”或者“-”，

**Comment by guanbo** [comment]
> 1.无法得知哪种商品销量较大；

目前商户范围内没有查看单品销售额的，在商店范围内可以查看销量排行。 @leonardean 说明我们这块还要调整。

> 2.会员分析力度不够，无法得知哪个会员的贡献度最大，无法查询会员的消费记录；

目前CRM部分的功能还没实现。已经在 #189 中单开问题。

> 3.会员余额不支持排序；

已在 #211 单开issue。

> 4.销售及相关记录支持导出excel等功能

已在 #212 单开issue

> 5.储值流水能明显看出账户中的余额是增还是减，比如前面加上“+”或者“-”，

已在 #213 单开issue
