### ISSUE TITLE
查看详细销售流水记录时，左侧树状菜单无反应

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/exprocrm#203]
点击销售流水——点击某条销售记录——显示详细销售记录时，点击左侧树状菜单，销售流水无反应。

**Comment by chenshun** [comment]
试了一下，似乎不是bug，如果想返回到原来的列表，需要点击右上角`X`关闭详情即可，不知道是不是想在左侧菜单加入跳转到列表的功能？
@guanbo

**Comment by guanbo** [comment]
对。应该是体验改善，很多人的使用习惯是点击左侧菜单以后回到列表界面。
