### ISSUE TITLE
查询时间段过大，提示不友好

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/exprocrm#207]
![image](https://f.cloud.github.com/assets/2062648/2481517/eec7b874-b0db-11e3-9805-3a027be4d44d.png)
进货查询页面下，时间段过大的情况下，提示不够友好，见上图！

**Comment by wangjing199408** [comment]
![image](https://cloud.githubusercontent.com/assets/6337119/2642281/7e547e54-bf06-11e3-8c71-e9e9b815d492.png)
@guanbo
