### ISSUE TITLE
密码修改需先确认原密码

### ISSUE THREAD

**Issue by xiaoyuxiong** [extensivepro/exprocrm#209]
点击右上角个人头像——修改密码，显示如下图：
![image](https://f.cloud.github.com/assets/2062648/2481605/30e0deb0-b0dd-11e3-8b2d-b9257aa1f666.png)
修改密码qian前需要先匹配原密码，否则不让修改，修改成功后，立即退出，需要用新密码登入（这个没试，如果已是这样操作，可忽略）。

**Comment by tsq** [comment]
@guanbo 用户修改密码时，需要填写原密码：而原密码和新密码是否一致的校验，如果不用服务端校验的话，能否直接在客户端校验，因为原密码可以在用户登录时存入localstorage。但又感觉这种做法在安全性上好像有点问题，你是怎么看的？

**Comment by guanbo** [comment]
- 密码等敏感信息尽可能不要存在本地
- 设置新密码可以用login的方式到服务端校验。
