### ISSUE TITLE
有关时间属性的填写

### ISSUE THREAD

**Issue by tsq** [extensivepro/exprocrm#22]
因不清楚，时间填选项（sinceAt、dueAt等）是通过何种方式创建,所以暂时想把他们的填入值设为一个时间点的毫秒数。

**Comment by guanbo** [comment]
@tsq @leonardean 我们时间保存单位全部用秒来保存。例如：

```
sinceAt = new Date.now()/1000;
```

Javascript通常是到ms，但iOS一般是到s，考虑到这些场景无需ms精度，所以取s为单位

**Comment by tsq** [comment]
@guanbo 可是我看到后台返回的都是以秒为单位，如
            "ownerID": "ae43a4a589a619c3",
            "type": "member",
            "name": "郭芳",
            "balance": 5000,
            "createdAt": 1389149081239,  
            "updateAt": 1389156617.253,
            "id": "ab8bc2164d69a95d"

**Comment by guanbo** [comment]
> @tsq @leonardean 我们时间保存单位全部用秒来保存。例如：

请关注我们上面的回复！！
