### ISSUE TITLE
店长密码重置

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#237]
## 需求
- 用户在iPad端密码遗忘或丢失iPad的情况，可以通过重置密码来保证iPad数据的安全性。
## 前置条件
- 用户已经把iPad下挂在用户名下的商店。
## 任务
- 提供界面重置iPad所在店的店长密码。
- 不需要提供原来的密码。

**Comment by chenshun** [comment]
重置密码后，POS端会提示密码不是数字，直接重设还是可以登录。在web端设置的密码到了POS登陆界面就变了。
其实丢失iPad只要把店长状态设置为`离职`，就无法登陆了，不需要重置密码。
