### ISSUE TITLE
库存查看失败

### ISSUE THREAD

**Issue by tsq** [extensivepro/exprocrm#24]
因后台dpd存在bug，导致前台取不到数据。dpd错误处为
            if(me.id !== merchant.owner.id) {
                error = new Error('disallow get skus');
                error.statusCode = 403;
                throw error;
            }
但是疑惑的是me.id为9f4b394aa96de9d2，而所有商户的拥有者的id都为9f4b394aa96de9d2，应该是相等的。

**Comment by guanbo** [comment]
你查库存的时候需要带querystring，将merchant的查询的返回的集合的owner.id全部为me.id
