### ISSUE TITLE
对商店的经纬度坐标进行记录

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#253]
## 需求

微信点餐在餐厅外的时候需要经纬度坐标，用来进行搜索周边的时候匹配。
## 方案
- 在商店管理中设置地址的时候同时打开地图标记出当前的坐标。
- 用户保存以后就将坐标信息保存到泛商汇。

**Comment by tsq** [comment]
@guanbo 这块的意思不明白。
