### ISSUE TITLE
商户商品标签管理

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#257]
## 需求

商户的商品管理中加入对商品分类标签的管理。
## 方案
- 在商品管理中可以对商品实现新增标签分类的功能
- 可以在商品详情中看到所有的分类
- 菜单中建议一个`品类管理`一级菜单项，下面包含商品管理和分类标签管理
- 分类标签管理中可以实现对标签的增删改查

**Comment by tsq** [comment]
分类标签是指，挂在‘’商户’和‘’菜’上的分类吗?如‘荤菜，蔬菜，冷盘’等。如果是，那么分类标签也就一个属性：他的名字，为他单独开4个页面做增删改查，感觉不值。

**Comment by guanbo** [comment]
要有个地方让用户知道我有哪些标签，而且这个地方就在商品的附近，很容易找到。

**Comment by guanbo** [comment]
@tsq 你卡在什么地方？

**Comment by tsq** [comment]
整个做的流程不清楚。
