### ISSUE TITLE
新注册的用户，销售流水列表虽然为空，但是页脚分页处显示错误

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#258]
如下图：
![image](https://cloud.githubusercontent.com/assets/3068259/2692614/24579a96-c3a5-11e3-9cf0-b76f60190d8e.png)
没有销售流水，但是却显示出其他商户的销售流水数量

**Comment by guanbo** [comment]
@wangjing199408 这个问题解决没有？

**Comment by wangjing199408** [comment]
解决了。
