### ISSUE TITLE
菜品选择类别时设计的不够好用

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#267]
![image](https://cloud.githubusercontent.com/assets/3068259/2715473/63ec3e9a-c50e-11e3-9d0f-39d3be721166.png)
如上图，选择`类别`需要先输入一个字，然后才会弹出类别，这样做似乎很鸡肋，因为`类别`也就是两三个字，输一个字跟输两三个字耗费的操作基本一样。
建议在输入选中`类别`的input时就直接显示已有的所有类别让用户选择，不需要先做输入。

**Comment by tsq** [comment]
@guanbo  已经改成下拉框选择了。可以Close了。
