### ISSUE TITLE
注册设备时存在的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#268]
![image](https://cloud.githubusercontent.com/assets/3068259/2715654/ddd2b71c-c512-11e3-9cdc-738a6108baea.png)
如上图，注册设备时存在下列问题：
- `归属商店`没有边框，tab选择输入时会直接跳过这一步；
- 选择商店时的loading时间过长；
- 注册成功后没有跳转到原先的设备列表页面。

**Comment by guanbo** [comment]
> 归属商店没有边框，tab选择输入时会直接跳过这一步；

已经不存在，其他还需要改进
