### ISSUE TITLE
商品详情未显示照片

### ISSUE THREAD

**Issue by wangjing199408** [extensivepro/exprocrm#272]
![image](https://cloud.githubusercontent.com/assets/6337119/2717804/04545142-c546-11e3-820f-77dbc3acb010.png)
新增商品，上传照片成功，再点击商品详情，未显示照片！

**Comment by guanbo** [comment]
@wangjing199408  以后提BUG请参考下面的形式

## 步骤
- 进入商品列表
- 选择XX商品进入详情

## 预期

可以看到照片

## 实际

无法看到照片

**Comment by guanbo** [comment]
@tsq 可能更文件名字的大小写有关。

**Comment by wangjing199408** [comment]
知道了！现在新增商品，进入详情，可以显示了！
