### ISSUE TITLE
商品详情无法保存和上传图片

### ISSUE THREAD

**Issue by wangjing199408** [extensivepro/exprocrm#273]
![image](https://cloud.githubusercontent.com/assets/6337119/2717832/61824400-c546-11e3-8d49-9aceaf95b3be.png)
商品详情，无法保存和上传(图片)。

**Comment by tsq** [comment]
@wangjing199408  你确定现在还不能上传吗？

**Comment by wangjing199408** [comment]
![image](https://cloud.githubusercontent.com/assets/6337119/2752091/3a646d42-c8fe-11e3-8dcb-5e6d37c541b1.png)
编辑时没有反应！

**Comment by tsq** [comment]
@wangjing199408 不要编辑原来的商品，要自己重新创建一个菜，再编辑。

**Comment by wangjing199408** [comment]
新建的可以。

**Comment by guanbo** [comment]
@tsq 设计时候就没有支持编辑？

**Comment by tsq** [comment]
原来的商品都不是菜，用的都是很久以前的逻辑，后来加了商品可以是菜，所以代码逻辑只考虑到菜的增删改查，因此对之前已经创建的商品，编辑功能不兼容。

**Comment by guanbo** [comment]
理论上应该是可以兼容前面的商品才对，mongodb是文档型的数据库，只要在dpd将属性加入，mongodb是不会对存入的东西做限制的。

已有商品兼容的问题先挂起，等稍后有时间再解决。

**Comment by tsq** [comment]
这个issue可以关闭了，至于兼容的问题，以后再解决。

**Comment by guanbo** [comment]
先挂着，后面找时间解决。
