### ISSUE TITLE
订单流水列表中存在的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#282]
![image](https://cloud.githubusercontent.com/assets/3068259/2748042/77c3d438-c7a1-11e3-8dd3-9a7da3d24174.png)
如上图，类型和状态显示需要更改，创建时间不正确。

**Comment by tsq** [comment]
@chenshun  更改是指，把类似booking,canceled等换成阅读性好一点的词语吗？时间的问题，是dpd那一侧的问题，可以将这个时间问题放在expro-future的issue中。

**Comment by guanbo** [comment]
> 时间的问题，是dpd那一侧的问题，可以将这个时间问题放在expro-future的issue中。

这个问题已经修复。

**Comment by guanbo** [comment]
> 把类似booking,canceled等换成阅读性好一点的词语吗？

@tsq 请参看[交互协议](https://github.com/extensivepro/expro-future-test/blob/master/webservice/interface/orders.md)调整文字说明。
