### ISSUE TITLE
订单模块查询功能暂时不能用

### ISSUE THREAD

**Issue by tsq** [extensivepro/exprocrm#291]
原先订单模块中查询是根据‘状态来查询的’, 如‘canceled, executed等’，但后来为了显示友好，列表界面上显示的是‘取消，履行等字样’，所以此时，用户在查询时输入‘取消，履行’等搜索条件时，会看不到结果。但是输入‘canceled,executed’还是可以查询的，不过，这显示不符合实际情况。

**Comment by guanbo** [comment]
搜索的时候不按状态来搜，最好的方式是由button group的形式来过滤不同的状态，例如github的issue
