### ISSUE TITLE
注册用户、创建商户。

### ISSUE THREAD

**Issue by wangjing199408** [extensivepro/exprocrm#293]
### 步骤
-  进入RMS
-  注册用户
-  登进，新建商户
### 问题
-  无法创建

**Comment by guanbo** [comment]
以下类容转自 #294 

> 原因：
> 新建商户时，需要将当前用户的身份证号码带到服务端，而新用户注册时，并没有要求填写身份证号 码。当前版本，用户要想新建商户成功，得先到‘我的设置’中填写身份证号，并刷新页面，不过这种挽救方式，对新用户来说是不可能知道的。

### 解决方案

在创建用户的时候强制要求输入身份证号码。请 @wangjing199408 实现。
