### ISSUE TITLE
商户LOGO管理

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#305]
## 需求

商户可以上传自家的头像。在当前商户管理中进行。
## 方案
- 商户可以上传1024x1024尺寸的图片作为自家LOGO
- logo文件的大小不能超过2M

**Comment by tsq** [comment]
dpd端并没有定义图片属性，你先定义一下，要存图片名和图片id

**Comment by guanbo** [comment]
已经在dpd上支持了 @tsq
