### ISSUE TITLE
外送管理

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#310]
## 需求
- 商户可以设定门店是否支持外卖。
- 如果支持外卖，还可以设置不送外卖的时间端。
## 方案
- 在商店管理中新增外卖开关
- 开关打开后可以设定不送外卖时间段，目前只支持一个时间段。

**Comment by tsq** [comment]
@guanbo  dpd中shop的config.json好像没变？属性名和类型要不你先定义好

**Comment by guanbo** [comment]
外送那块泛商汇service还没有调整，你可以等我调整以后，这里会有commit通知显示。
