### ISSUE TITLE
商户公众号管理

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#311]
## 需求

商户要有微信公众号的信息，方便用户在关注该商户的微信公众号自动成为会员。
## 方案
- 在商户管理中加入公众号的设定管理（gh_开头的公众号原始编号）

**Comment by tsq** [comment]
@guanbo ‘公众号的设定管理’是指：在商户的增删改查中要加入‘weixin’吗？我看了dpd那侧的config.json。‘weixin’被定义成了一个对象，这又是什么意思？还有‘gh_开头的公众号原始编号’这句话又是什么意思？

**Comment by guanbo** [comment]
请参看[商户的交互协议](https://github.com/extensivepro/expro-future-test/blob/master/webservice/interface/merchants.md)
