### ISSUE TITLE
会员管理，详情编辑

### ISSUE THREAD

**Issue by wangjing199408** [extensivepro/exprocrm#319]
![image](https://cloud.githubusercontent.com/assets/6337119/2838127/67194fc6-d02c-11e3-85cc-800670b511f5.png)
![image](https://cloud.githubusercontent.com/assets/6337119/2838128/7404dea8-d02c-11e3-9b04-f8d04c737485.png)
未显示身份证号码，
会员编码修改保存过后，显示的编码还是未修改前的。

**Comment by guanbo** [comment]
> 会员编码修改保存过后，显示的编码还是未修改前的。

会员编码现在设计是不能修改的。
