### ISSUE TITLE
库存记录中，核销库存存在的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#322]
![image](https://cloud.githubusercontent.com/assets/3068259/2838209/548f65be-d02e-11e3-97f3-cf18fb1fb1aa.png)
如上图，`核销`时，如果不输入`进货价格`，那么在库存记录中就会有如上显示。

**Comment by tsq** [comment]
@chenshun  将‘进货价格’设为必填可以吗？
