### ISSUE TITLE
库存记录中的删除不能正常使用

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#324]
![image](https://cloud.githubusercontent.com/assets/3068259/2838229/fe3ed9fa-d02e-11e3-84d3-684c81e2bc84.png)
如图，无论是批量删除还是单个删，目前都删不掉。

**Comment by wangjing199408** [comment]
@chenshun 库存记录在交互上没有删除，看了下

**Comment by tsq** [comment]
@guanbo  库存中有个属性叫‘status’,删除库存是否也是将他的值更新为'removed'.

**Comment by guanbo** [comment]
目前库存在设计上没提供删除功能，当需要减计库存的还是，走的是库存核销的方式。

所以，在库存管理中先不提供删除功能。
