### ISSUE TITLE
商品图片建议限制尺寸大小，或者可以选择删除图片

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#325]
![image](https://cloud.githubusercontent.com/assets/3068259/2838260/39981df8-d030-11e3-9998-9c0fa7e1260a.png)
如上图，加了一张图使得整个商品详情的显示无法直视，建议在页面中固定一块显示图片的区域，无论用户上次什么样的图都不至于破坏页面布局。或者给个删除图片的功能，如果发现图片不合适也可以自己删掉。

**Comment by guanbo** [comment]
已经合并到 #366 中
