### ISSUE TITLE
进出货时，部分存在商品不能直接带出信息

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#326]
如图：
![image](https://cloud.githubusercontent.com/assets/3068259/2838922/c2953e1c-d03d-11e3-925e-b2a777670725.png)
![image](https://cloud.githubusercontent.com/assets/3068259/2838923/daded30c-d03d-11e3-86d2-bfebf6b97b9b.png)
该商品确实存在于商户下，但是在进货与核销时并没能直接带出该商品的信息。

**Comment by tsq** [comment]
@guanbo  当商品编码（code）以‘0’开头时，查询商品会有问题。
调查发现：若请求url为：http://localhost:2403/items?code=038000846625,但是到了dpd那边，url就会变成
了：                  http://localhost:2403/items?code=38000846625；即038变成了38，0被删除了，所以，再去查code为：38000846625就不会查到。
注：
1.item中config.json关于code的定义为‘string’。
2.get.js为

```
if (!internal) {
    if(!me) {
        var error = new Error('please login');
        error.statusCode = 401;
        throw error;
    }
}
```
