### ISSUE TITLE
以前无类别的商品，在编辑时，无法输入类别

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#327]
![image](https://cloud.githubusercontent.com/assets/3068259/2838958/abd2cf90-d03e-11e3-8185-e06e84429009.png)
如上图，这是以前的商品，没有`类别`，在编辑时，`类别`里无法做任何输入。建议这里`类别`改成只供选择不给输入。需要类别的一律去`标签管理`中添加。

**Comment by guanbo** [comment]
> 建议这里类别改成只供选择不给输入。需要类别的一律去标签管理中添加。

这样不够方便。
