### ISSUE TITLE
有时，在选择商店option中的商店与列表中出现的信息不一致

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#328]
![image](https://cloud.githubusercontent.com/assets/3068259/2839173/53f5dbec-d042-11e3-99bb-f383182c7d9e.png)
如上图，点击`库存记录`，默认显示商店`华仔理发店`，但是列表中的数据并非该商店下的数据，刷新一下后显示正常：
![image](https://cloud.githubusercontent.com/assets/3068259/2839184/8c080c26-d042-11e3-9882-f4bc7f6c2bfa.png)

**Comment by tsq** [comment]
在 #333 中已经对此issue进行了修复，@chenshun,请顺子检查一下。

**Comment by tsq** [comment]
@guanbo  @chenshun  这个issue应该可以关了。
