### ISSUE TITLE
订单流水筛选方式建议调整，并且需要加入“全部”选项

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#329]
![image](https://cloud.githubusercontent.com/assets/3068259/2839221/87b25806-d043-11e3-8507-60944fdec223.png)
如图，现在筛选方式是一排对应的按键，一开始我以为是一些功能键。这种方式建议调整，筛选还是用类似选择商店的方式更符合整体风格，或者可以用一个按键点击下拉的方式展开，并且选项中应该加入`全部`。

**Comment by guanbo** [comment]
@tsq 请优先处理。
