### ISSUE TITLE
新注册的用户，缺少一些必要的指引

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#339]
新注册的用户数据都是空的，要正常使用需要先创建`商户`，然后再创建`商店`、`会员`、`雇员`等，但是实际使用中，用户注册完后并没有类似指引，很可能不知道该怎样上手，并且目前商户的显示也不合适，如下图：
![image](https://cloud.githubusercontent.com/assets/3068259/2872614/2edddf48-d36d-11e3-91de-7ccc8a9d01d7.png)
建议改善，例如：当用户注册首次登陆时跳转到`当前商户`页面，并且提示需要立即创建`商户`，然后点击一下直接开始创建。

**Comment by tsq** [comment]
由于商户、商店对于整个系统非常重要，所以现在将登录与注册功能做了如下修改：
登录：
1.登录成功后，会先检查当前用户是否有商户，有则放行，直接进入主页面，没有，则弹出新建商户的modal。
注册：
1.用户成功注册后，会先进入‘新建商户’的modal，创建完商户后，会进入‘新建商店’的modal，创建完商店后则进入主页面。

总之，用户进入RMS系统的主页面前，必须得先创建一个商户。
