### ISSUE TITLE
会员管理中，select与search框没有作用

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#34]
### 步骤
1. 登陆泛商会CRM
2. 点击`会员管理`
### 结果

可以看到，左上角select框没有作用，因为数据较多，页面加载时总是先跳出表格，在跳出数据。如下图：
![image](https://f.cloud.github.com/assets/3068259/1928433/328142c6-7e80-11e3-84c8-552129eee3e3.png)
### 期望

select框可以指定显示数量，页面中的数据与表格同时加载。

**Comment by guanbo** [comment]
@leonardean 是否已经解决merge？

**Comment by leonardean** [comment]
已经merge

**Comment by guanbo** [comment]
@chenshun 请验证关闭
