### ISSUE TITLE
修改商品标签时，商品标签与商户标签的同步

### ISSUE THREAD

**Issue by tsq** [extensivepro/exprocrm#340]
@guanbo @chenshun 
现在，crm中对item修改标签时，只是发送了一个update请求，只更新当前item的tags属性，并没有与商户下面的标签同步。即：若item中新增了一个tag后，merchant中不会看到这个tag。
一点意见：编辑item的标签时：标签只能通过一个<select>来进行选择（用户无法手动填写），当用户觉得要新增一个标签时，可以点击<select>旁的一个<button>，弹出一个modal，让用户新建一个tag，而此时的tag是直接挂载在merchant上的。当创建完后，<select>中会新增刚刚创建的tag。最后，当用户保存编辑结果时，item只需要更新自己的tag就可以了，而不需要再去同步商户下的tag。

**Comment by guanbo** [comment]
> 一点意见：编辑item的标签时：标签只能通过一个来进行选择（用户无法手动填写），当用户觉得要新增一个标签时，可以点击旁的一个，弹出一个modal，让用户新建一个tag，而此时的tag是直接挂载在merchant上的。

这块只是方便了开发，不方便使用。如果仅仅是临时的措施可以接受，但东西不好用，用户就不用了。

> 现在，crm中对item修改标签时，只是发送了一个update请求，只更新当前item的tags属性，并没有与商户下面的标签同步。即：若item中新增了一个tag后，merchant中不会看到这个tag。

在更新了item的同时也更新merchant的标签数组，如果indexof不到的话。
