### ISSUE TITLE
商品标签没有与商品关联上

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#353]
### 步骤
1. 新增一个标签，例如`饮料`
2. 编辑一种商品，例如`可乐`，把他的`类别`设置成`饮料`
3. 用客户端搜索该店铺，并且查看`饮料`下的商品
### 结果

`饮料`下并没有出现刚才的商品
### 期望

标签可以关联到商品

**Comment by tsq** [comment]
@chenshun ’用客户端搜索该店铺，并且查看饮料下的商品’  中的‘客户端’是指IPad，还是在RMS上的某个地方？
