### ISSUE TITLE
进货统计中存在的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#362]
![image](https://cloud.githubusercontent.com/assets/3068259/2898814/5c77a91a-d5a8-11e3-9b4b-5a7379bc1e50.png)
如上图，两家商店的进货统计，在柱状图中两家合并了，没有体现各家商店的进货情况。

**Comment by tsq** [comment]
统计这块我重来没接触过，这块任务我完成不了。

**Comment by guanbo** [comment]
可以放在后面一点搞，但不能拒绝新东西。
