### ISSUE TITLE
进货统计，销售统计。

### ISSUE THREAD

**Issue by wangjing199408** [extensivepro/exprocrm#364]
![image](https://cloud.githubusercontent.com/assets/6337119/2911518/7ec3a99a-d65e-11e3-85ed-e3c374acf715.png)
![image](https://cloud.githubusercontent.com/assets/6337119/2911520/894f2a74-d65e-11e3-9f4c-19c8535d2064.png)
### 问题

显示已删除的商店!

**Comment by leonardean** [comment]
多店时数据获取请求：
http://service.fankahui.com:2403/statistics?end=16198&keyID=9f4305b2e75c28ed&keyID=4fd62f2e233398c9&keyID=135f9da6a13bc86b&keyID=d08d72754e6d88ca&keyID=7bdde84727484973&keyID=3e2654657aa5287b&keyID=8cde000edbe5a9b1&keyID=ea16dd3638babafb&keyID=86430000c1fafa5f&keyID=ff3a61374e2c9b12&limit=1000&period=daily&start=16168&target=bills
无法获取statistic 数据, 而获取整个商户的统计数据时：
http://service.fankahui.com:2403/statistics?end=16198&keyID=e20dccdf039b3874&limit=1000&period=daily&start=16168&target=bills
有数据。
经调查，即便把每个商店keyID带入逐一query也没有一个商店有销售数据，所以可能是商店销售数据的mapreduce有问题

**Comment by guanbo** [comment]
第一个问题与 extensivepro/expro-future-test#647 重复

@wangjing199408 下次尽可能将两个问题拆分独立的issue
