### ISSUE TITLE
查询商户时的意外发现

### ISSUE THREAD

**Issue by tsq** [extensivepro/exprocrm#365]
![bb0fe12c-7a35-4325-8305-404aa905dfb9](https://cloud.githubusercontent.com/assets/6081537/2913109/e7ef6f1c-d686-11e3-9a49-1b3f66a411e3.png)

意外发现，这个用户（本地自测数据）竟然有两个同名的商户，它竟然绕过了dpd关于创建merchant的校验，更奇怪的是，这两个商户的创建时间是同一时刻。调研了一下，但是没发现原因，
之后，也尝试过创建一个商户后，再创建一个同名的商户，都可以被dpd拦截住，不允许创建。

dpd关于merchant创建时的校验

```
dpd.merchants.get({name: this.name}, function (results, error) {
    if (results.length > 0) {
        cancel('merchant name exist', 400);
    } else {
     ......
```

**Comment by guanbo** [comment]
- 每次新增这个用户都会出现2条记录？

**Comment by tsq** [comment]
当给这个用户再创建一个商户后，只有1条记录。

**Comment by tsq** [comment]
![e0a8eab6-544c-4220-a150-df8c07744340](https://cloud.githubusercontent.com/assets/6081537/2913323/75214be6-d68a-11e3-9d2a-3e58390556c6.png)
id为‘ aa7d0df34b6f184f’商户下新建的商店，也出现了同样的问题。他们的创建时间，名字都一样。
不过现在再去尝试，却不会出现这样的问题了，很奇怪。
