### ISSUE TITLE
商品详情页面图片展示改善

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#366]
## 问题
- 商品详情中图片过大导致整个表格变形，需要限制图片的宽度 < 1024。
- 图片需要独立于表格，以照片集的形式展现。

![2014-05-08 4 20 33](https://cloud.githubusercontent.com/assets/712444/2913257/ada4bf3a-d689-11e3-916c-dc510b07e7cd.png)

**Comment by tsq** [comment]
'照片集的形式' ，这是一个什么样的形式？有Demo吗？

**Comment by guanbo** [comment]
没有，几张图并排显示即可。这样的效果，用户没办法接受的。发挥主观能动性。

**Comment by tsq** [comment]
![deea600d-f49f-4541-8895-7377c5526f48](https://cloud.githubusercontent.com/assets/6081537/2913473/8516bb88-d68c-11e3-82a9-2656b4c14dd2.png)
用angular for bootstrap中的Carousel可否，它可以用鼠标点击来回滚动。

**Comment by guanbo** [comment]
可以，还有把详情页中那个头像干掉。
