### ISSUE TITLE
营业日报

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#369]
## 需求

以日为单位，集中统计当天经营的数据，包括以下内容
- 营业额
  - 总额、次数、客单价（=总额/次数）
- 现金流
  - 总收入（=现金收入+微信支付收入）、现金收入、微信支付收入
- 利润
  - 总毛利润（=（成交价-进货均价）x数量）
- 交易明细
  - 以列表的形式展现当天完成的交易。
## 方案
- 在左侧菜单建立一级目录——营业日报
- 打开日报以后，以多个box分别列支需求中数据。

**Comment by tsq** [comment]
得把这些数据从哪里取写出来，不然我不知道怎么去取。

**Comment by guanbo** [comment]
- 需要深入了解业务的关系，不能只考虑代码层面的实现。
- 日营业额实际就是bill的统计对数据库的mapReduce这块已经有了，获取的途径也是通过statis接口。
- 其他可以参考营业额来做。
- 毛利润有可能因为没有进货操作，而没有平均进价，这种情况以平均进价为0来处理。

**Comment by tsq** [comment]
是不是只显示当天的bill信息，其他时间的都不用管。

**Comment by guanbo** [comment]
是的，可以参考service中resources/statistic/get.js和datamining/mr-bills.js
