### ISSUE TITLE
商户管理中，部分数据不应该在列表中呈现

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#38]
如下图：
![image](https://f.cloud.github.com/assets/3068259/1937123/18c21c7a-7f1b-11e3-934e-949916ff1fee.png)

图中红色圈出的部分是我认为不该在列表中呈现的数据，数据太多给用户感觉复杂、繁琐，不是重要的数据尽量放在edit里面呈现。
另外，既然是商户管理，就应该把商户名放在第一列。

**Comment by guanbo** [comment]
商户业主一列拿掉
