### ISSUE TITLE
营业报表中“利润”的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#380]
![image](https://cloud.githubusercontent.com/assets/3068259/2970309/c92c2336-db59-11e3-9e5c-6207d4b2ce38.png)
如图所示，添加了几笔交易后，毛利润就一直显示为0

**Comment by tsq** [comment]
算利润，要求商品必须含有成本属性（item下的itemSkus属性），而之前的商品都没有这个属性，所以要正确的算出利润，必须交易的商品都有成本属性（现在先建库存的时候都会给商品自动算成本了）。上面之所以会显示0，是因为其中的一个商品‘劲爆鸡米花’没有成本价，导致运算报错，程序挂掉。
