### ISSUE TITLE
营业报表中“现金流”问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#381]
![image](https://cloud.githubusercontent.com/assets/3068259/2970857/752383c0-db62-11e3-9a06-bb43d8984b2a.png)
如上图，`现金支付`实际值是`1204.5`，显示值为`1205`。
引用[wiki](http://wiki.mbalib.com/wiki/%E8%90%A5%E4%B8%9A%E7%8E%B0%E9%87%91%E6%B5%81%E9%87%8F)中的营业现金流公式：`现金流量（NCF）= 营业收入一付现成本一所得税`，这里不考虑税，应该统计出`营业收入`与`付现成本`，`营业收入`应该是所有商品销售额加上会员充值的总和，`付现成本`应该是进货支出成本、退款、冲减的总和。

**Comment by tsq** [comment]
现金流已做过mapreduce,没问题的话可以关闭了。
