### ISSUE TITLE
关注公众号成为会员的，会员账户没有金额，消费记录不应该在储值流水中出现

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#393]
![image](https://cloud.githubusercontent.com/assets/3068259/2995771/e7c9aacc-dce2-11e3-8ea6-0914bf7f1d1c.png)
如上图，这是关注公众号的会员，这些交易流水不是会员储值流水，不应该出现。

**Comment by guanbo** [comment]
已经解决
