### ISSUE TITLE
图片文件上传支持裁剪

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#395]
## 需求

目前由于上传的图片过大，导致手机端加载的时间过长。需要对上传图片做限制按手机的展现的需要裁剪图片到合适大小。
## 方案
- 在上传的图片中用透明框框住准备上传图片的部分，用户可以移动框位置来调整需要的图片部分。
- 图片的大小目前限制在400x400的尺寸上。
## 参考

[FileAPI](http://mailru.github.io/FileAPI/#en/FileAPI.Image.crop) - javascript的图片处理三方库
[微信精选商品](http://mm.wanggou.com/promote/xin_index.shtml) - 最终期望在我们公众号上的展现效果

**Comment by tsq** [comment]
商品图片已经增加裁剪功能，没问题的话，请关闭。 @chenshun  @guanbo
