### ISSUE TITLE
之前“储值流水”改为“账单流水”的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#396]
![image](https://cloud.githubusercontent.com/assets/3068259/3010715/7d1f069a-df1c-11e3-9a2a-78b1dcb3cd63.png)
之前统计的是储值流水，就是所有bill相关的交易，现在改为`账单流水`是否应该把所有的账单记录都在此统计？

**Comment by guanbo** [comment]
应该是所有bill
