### ISSUE TITLE
员工管理列表中，部分数据不需要显示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#40]
如图所示：
![image](https://f.cloud.github.com/assets/3068259/1937193/c8017bee-7f1c-11e3-81ee-a7703e27c6d8.png)

红色圈出的数据不需要在列表中呈现。同时`创建时间`改为`入职时间`，并且`状态`放置在入职时间后面。

**Comment by guanbo** [comment]
工号和职务还是建议保留，但排列的顺序最好调整一下。
