### ISSUE TITLE
库存记录应该放入品类管理中更合适

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#400]
![image](https://cloud.githubusercontent.com/assets/3068259/3024168/3f999d20-dff4-11e3-94c5-e4a8b954576c.png)
如上图，`库存记录`建议归为`品类管理`，让商品的进出货与商品更近。

**Comment by guanbo** [comment]
库存将来会单独出来作为一个独立的模块，包括库存记录、库存预警、门店调货等。将来会放在一起。现在只是暂时放在这里。
