### ISSUE TITLE
订单中的顾客与销售流水中的顾客不统一

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#402]
![image](https://cloud.githubusercontent.com/assets/3068259/3024684/29b5fb9a-dffc-11e3-9754-bc4c49149e22.png)
![image](https://cloud.githubusercontent.com/assets/3068259/3024686/3e52a788-dffc-11e3-9d41-914147262ce2.png)
上面两张图分别是订单流水与销售流水，同样的一笔交易，订单流水顾客显示的是收货人姓名，而销售流水中的顾客显示的是购买者。
`订单流失`也应该显示购买者姓名，有需要的话，可以在列表中加入`收货人`。

**Comment by guanbo** [comment]
> 上面两张图分别是订单流水与销售流水，同样的一笔交易，订单流水顾客显示的是收货人姓名，而销售流水中的顾客显示的是购买者。

你上图显示的不是同一个订单和对应的交易，注意最后3位位数。

> 订单流失也应该显示购买者姓名，有需要的话，

那个`曹`确实只输入了一个字。中午的客户

> 有需要的话，可以在列表中加入收货人。

@tsq 请子啊列表中加入收货人姓名。

**Comment by chenshun** [comment]
> 你上图显示的不是同一个订单和对应的交易，注意最后3位位数。

既然如此，就不需要加入收货人了，列表本身就已经比较拥挤，详情中能看到就OK了。
