### ISSUE TITLE
团购活动管理

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#411]
## 需求
- 可以从商品中选择单品建立微团购活动的模板，设定活动时间，成团人数要求为3~5人。可以编辑团购活动的说明和图片。
- 可以设定积分奖励的数量，当成团以后积分会自动到参团的会员积分账户上。
- 团购活动的列表，可以查看到当前已经建立的团购活动。点击后可以看到微团购活动模板的详情。
- 团购活动编辑完成后可以对外发布。一旦对外发布，将不能变更团购的基本信息，包括活动时间、活动规则、活动商品等。
- 团购发布以后，用户可以自行组团，发起组团以后可以在活动详情中看到已经组团的记录。
- 团购结束时间到以后将自动将状态切换到已经结束，将不再接受组团申请。
## 方案
- 在一级菜单中建立营销管理，在二级菜单中建立微团购管理的入口。
- 进入团购管理后，将团购活动的模板以列表形式展现出来。
- 进入活动模板的详情后，可以看到具体参数以外，还可以看到当前活动的状态。

---

@chenshun 请绘制原型和时序图，完成后指派给 @tsq 实现。

**Comment by chenshun** [comment]
[团购原型](https://projects.invisionapp.com/d/main#/console/292578/24267512/preview)
@guanbo  @tsq 请preview一下。

**Comment by chenshun** [comment]
原型已经修改
- [团购原型](https://projects.invisionapp.com/d/main#/console/292578/24267512/preview)
- [时序图](https://projects.invisionapp.com/d/main#/console/292578/24378554/preview)

请preview。
