### ISSUE TITLE
会员储值管理，存在的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#44]
参照Issue #10 ，应该要展现的是`储值流水记录`

如图所示：
![image](https://f.cloud.github.com/assets/3068259/1937453/c3abed6a-7f24-11e3-97a8-791b6df17876.png)
- `储值管理`改为`储值流水`，考虑`储值管理`以后会和`会员储值账户管理`冲突
- 图中红色方框选中的数据不需要在列表中呈现
- 交易类型中，以`deal=交易`、`prepay=充值`、`return=退款`调整
- `创建日期`改为`日期`
- 加入`顾客`、`经手人`与`金额`

**Comment by tsq** [comment]
@guanbo 这个issue在 #37已改正，请给予关闭

**Comment by guanbo** [comment]
@chenshun 请验证

**Comment by chenshun** [comment]
![image](https://f.cloud.github.com/assets/3068259/1961758/3e04059a-827a-11e3-9ad7-63a84afd52a8.png)
- 当前只显示了会员的充值记录，而交易和退款的记录并没有体现
- 金额的显示不规范
- 经手人显示不正确

**Comment by chenshun** [comment]
@tsq 缺少`日期`，建议放在首列。
