### ISSUE TITLE
会员管理中，新增会员要输入的信息太多。

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#48]
如图所示：
![image](https://f.cloud.github.com/assets/3068259/1938623/02e308f4-7f4f-11e3-81e9-7b0981cbfc92.png)

上面很多都不应该让用户来填，用户只需要输入会员的重要资料就行。类似`商户`、`商店`这些信息应该通过其他方法自动得到。
同时自动带出的数据应该在创建时隐藏掉，比如上面的`创建日期`。

**Comment by guanbo** [comment]
@leonardean 请先设计导航方式界面原型，然后实现。
