### ISSUE TITLE
会员详情展示中，部分数据不需要显示

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#54]
如图所示：
![image](https://f.cloud.github.com/assets/3068259/1938991/c1cccca2-7f57-11e3-8cd9-129fd338e905.png)
- 上图红色方框选中的数据不需要呈现给用户。
- `开始时间`改为`加入时间`，`结束时间`改为`有效期至`。
- `postPoint=当前积分`，`postTotalPoint=累计积分`
- 加入`身份证`、`账户金额`

**Comment by chenshun** [comment]
@tsq 
上面的`加入时间`和`有效期至`被你去掉了，椭圆形圈出的是代表要修改的！

**Comment by tsq** [comment]
@chenshun 
了解。
