### ISSUE TITLE
商户分析中，关于选择时段的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#74]
当我点击`weeks`来选择时段，选中的仍然是一天。如下图，鼠标移动在`16`：
![image](https://f.cloud.github.com/assets/3068259/1992815/02c60778-84cb-11e3-8b24-1c9b0c6867c3.png)
期望当选择`weeks`时，鼠标移动上去默认是一周。

**Comment by leonardean** [comment]
已解决，解决方案为用户自行选择时间段
