### ISSUE TITLE
库存管理中需要给数据排列顺序

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#75]
目前列表中查询出的库存记录似乎没有排列顺序，新的库存记录总是在列表的最后一页才能看到。
应该改为时间由近到远，即按照时间，让最新的库存记录总是出现在列表最前面，因为用户更加关心新的库存记录。

**Comment by guanbo** [comment]
不光是库存，销售也没有按销售时间从近到远排序

**Comment by tsq** [comment]
这个issue已经改好了，在basic.js中增加了

```
$scope.sortOptions = {createdAt:-1}
...
$scope.params.$sort = $scope.sortOptions;
```

这个改动是之前有个commit提交的，可能是你或者崭文做的。
请关闭这个issue。@guanbo
