### ISSUE TITLE
员工管理，列表分页的问题

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#76]
如下图：
![image](https://f.cloud.github.com/assets/3068259/1992967/e2ba34cc-84cf-11e3-8e35-287414a3c8c2.png)
员工总计分为三页，第一页只显示了3名。
可能是把其他店的员工数量也算进来了，不过没有在列表中显示。
期望显示商户内所有员工，并且加入`商店`属性。

**Comment by guanbo** [comment]
已经修复
