### ISSUE TITLE
列表左下角默认显示的信息不正确

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#86]
如下图所示，各个列表左下角默认数量始终不变，只有在search框中输入查询条件，点击`搜索`之后才会变化。
![image](https://f.cloud.github.com/assets/3068259/2192781/f7952246-986e-11e3-9e1d-1960b7ac0861.png)
期望左下角默认的显示总是正确。

**Comment by tsq** [comment]
@guanbo 请关闭 issue 86
