### ISSUE TITLE
主界面框架调整

### ISSUE THREAD

**Issue by guanbo** [extensivepro/exprocrm#89]
## 问题
- 目前的左侧菜单过于扁平，界面比较乱。
- 由于我们是支持一个用户可以有多个商户，而主要用户是一个商户的。每次要看具体数据的时候需要先选择商户以后在看数据。
## 期望
- 有很多不常用功能可以收纳到二级界面，主体上分为常用的放第一级，例如销售、进货、盘点统计、控制面板（待设计）、基础信息、个人设置等。
- 需要引入默认商户机制，在登录以后直接展现改默认商户的数据，商户可以切换。
## 任务
- @chenshun 请在 @leonardean 原型基础上完善上述低保真原型。
- @leonardean 和 @tsq 请在 @chenshun 完成后上invisonapp吐槽，过期不吐槽的则认为是无异议。
- @chenshun 吐槽完毕后请按定稿的原型着手实现。

**Comment by chenshun** [comment]
原型修改如下：
- 对界面布局做了一点改动
- 增加了`商户设置`与`用户设置`这两个模块的原型
- 改变左边菜单内容的顺序

[参考原型](https://projects.invisionapp.com/d/main#/console/658683/16076223/preview)

@leonardean   @tsq
