### ISSUE TITLE
关于统计销售页面的一些建议

### ISSUE THREAD

**Issue by chenshun** [extensivepro/exprocrm#97]
![image](https://f.cloud.github.com/assets/3068259/2267875/64f82e9e-9ec0-11e3-936c-f4bf7f3bd559.png)
如上图所示：
- 椭圆圈出的两处日期显示重复，建议把日期的显示与设置结合起来，直接点击显示的日期就可以进行设置
- 方形圈出的设置商店也可以结合，把`所有商店`变成一个默认的selectOption代替`选择商店`
- `统计时段`与`统计单位`可以去掉，因为这两个功能很明显，不需要说明
- 把所有设置时间、单位的功能键结合一下，放到图表最上面，使界面风格更加简洁一点

**Comment by guanbo** [comment]
> 椭圆圈出的两处日期显示重复，建议把日期的显示与设置结合起来，直接点击显示的日期就可以进行设置
> 方形圈出的设置商店也可以结合，把所有商店变成一个默认的selectOption代替选择商店

同意

> 统计时段与统计单位可以去掉，因为这两个功能很明显，不需要说明

还是有必要保留，但建议放在一排。

> 把所有设置时间、单位的功能键结合一下，放到图表最上面，使界面风格更加简洁一点

严重同意

**Comment by chenshun** [comment]
> 还是有必要保留，但建议放在一排。

我是指图中画出底线的那八个字完全可以拿掉~~

**Comment by leonardean** [comment]
已优化，如下图：
![img](http://www.mftp.info/20140301/1393902115x-564177008.png)
